4-not_found_page_404

diff --git a/web_server/4-not_found_page_404 b/web_server/4-not_found_page_404
--- a/web_server/4-not_found_page_404
+++ b/web_server/4-not_found_page_404
@@ -1,9 +1,36 @@
 #!/usr/bin/env bash
-# Install nginx on your web-01 server
-apt-get -y update
-apt-get -y install nginx
-echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null
-sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
-echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
-sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
-service nginx restart
+
+# Update package lists
+apt-get update
+
+# Install nginx
+apt-get install -y nginx
+
+# Create a custom 404 error page
+echo "<!DOCTYPE html>
+<html lang=\"en\">
+<head>
+    <meta charset=\"UTF-8\">
+    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
+    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
+    <title>404 Not Found</title>
+</head>
+<body>
+    <h1>Ceci n'est pas une page</h1>
+</body>
+</html>" > /usr/share/nginx/html/404.html
+
+# Update Nginx configuration to use the custom error page for 404 errors
+sed -i '/^    location \/ {/a \
+        error_page 404 /404.html;' /etc/nginx/sites-available/default
+
+# Verify nginx configuration
+nginx -t
+
+# Restart nginx if the configuration is valid
+if [ $? -eq 0 ]; then
+    /etc/init.d/nginx reload
+else
+    echo "Nginx configuration is invalid. Please check the configuration file."
+fi
+
